-- 006_rag.sql
-- RAG import, parsing, chunking, embedding, keyword indexing, retrieval, rerank, and evidence gate tables.

CREATE TABLE IF NOT EXISTS rag_source (
    id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_key    VARCHAR(120) NOT NULL,
    name          VARCHAR(200) NOT NULL,
    type          VARCHAR(50) NOT NULL,
    uri           VARCHAR(1000) NOT NULL DEFAULT '',
    description   TEXT,
    owner         VARCHAR(100) NOT NULL DEFAULT '',
    status        VARCHAR(20) NOT NULL DEFAULT 'active',
    config        JSON,
    metadata      JSON,
    created_at    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at    DATETIME(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_rag_source_key (source_key),
    INDEX idx_name (name),
    INDEX idx_type (type),
    INDEX idx_owner (owner),
    INDEX idx_status (status),
    INDEX idx_deleted_at (deleted_at),
    INDEX idx_type_status_deleted_at (type, status, deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rag_document (
    id             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    document_key   VARCHAR(120) NOT NULL,
    source_id      BIGINT UNSIGNED NOT NULL,
    title          VARCHAR(500) NOT NULL,
    type           VARCHAR(50) NOT NULL DEFAULT 'unknown',
    uri            VARCHAR(1000) NOT NULL DEFAULT '',
    author         VARCHAR(200) NOT NULL DEFAULT '',
    version        VARCHAR(100) NOT NULL DEFAULT '',
    summary        TEXT,
    content_hash   VARCHAR(128) NOT NULL DEFAULT '',
    status         VARCHAR(20) NOT NULL DEFAULT 'pending',
    parser_name    VARCHAR(80) NOT NULL DEFAULT '',
    chunk_count    INT NOT NULL DEFAULT 0,
    metadata       JSON,
    created_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at     DATETIME(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_rag_document_key (document_key),
    INDEX idx_source_id (source_id),
    INDEX idx_title (title),
    INDEX idx_type (type),
    INDEX idx_content_hash (content_hash),
    INDEX idx_status (status),
    INDEX idx_deleted_at (deleted_at),
    INDEX idx_source_status_deleted_at (source_id, status, deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rag_parsed_document (
    id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    document_id   BIGINT UNSIGNED NOT NULL,
    parser_name   VARCHAR(80) NOT NULL DEFAULT '',
    content_text  LONGTEXT,
    structure     JSON,
    sections      JSON,
    status        VARCHAR(20) NOT NULL DEFAULT 'pending',
    error         TEXT,
    metadata      JSON,
    created_at    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at    DATETIME(3) DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX idx_document_id (document_id),
    INDEX idx_parser_name (parser_name),
    INDEX idx_status (status),
    INDEX idx_deleted_at (deleted_at),
    INDEX idx_document_status_deleted_at (document_id, status, deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rag_chunk (
    id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    chunk_key       VARCHAR(120) NOT NULL,
    document_id     BIGINT UNSIGNED NOT NULL,
    source_id       BIGINT UNSIGNED NOT NULL,
    ordinal         INT NOT NULL DEFAULT 0,
    title           VARCHAR(500) NOT NULL DEFAULT '',
    content         LONGTEXT,
    content_hash    VARCHAR(128) NOT NULL DEFAULT '',
    location        VARCHAR(500) NOT NULL DEFAULT '',
    token_estimate  INT NOT NULL DEFAULT 0,
    strategy        VARCHAR(50) NOT NULL DEFAULT '',
    metadata        JSON,
    created_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at      DATETIME(3) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_rag_chunk_key (chunk_key),
    INDEX idx_document_id (document_id),
    INDEX idx_source_id (source_id),
    INDEX idx_ordinal (ordinal),
    INDEX idx_content_hash (content_hash),
    INDEX idx_strategy (strategy),
    INDEX idx_deleted_at (deleted_at),
    INDEX idx_document_ordinal_deleted_at (document_id, ordinal, deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rag_embedding (
    id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    chunk_id     BIGINT UNSIGNED NOT NULL,
    model        VARCHAR(120) NOT NULL,
    dimension    INT NOT NULL DEFAULT 0,
    vector_ref   VARCHAR(200) NOT NULL DEFAULT '',
    vector_hash  VARCHAR(128) NOT NULL DEFAULT '',
    status       VARCHAR(20) NOT NULL DEFAULT 'pending',
    error        TEXT,
    metadata     JSON,
    created_at   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at   DATETIME(3) DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX idx_chunk_id (chunk_id),
    INDEX idx_model (model),
    INDEX idx_vector_ref (vector_ref),
    INDEX idx_vector_hash (vector_hash),
    INDEX idx_status (status),
    INDEX idx_deleted_at (deleted_at),
    INDEX idx_chunk_model_deleted_at (chunk_id, model, deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rag_keyword_index (
    id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    chunk_id     BIGINT UNSIGNED NOT NULL,
    index_name   VARCHAR(120) NOT NULL,
    document_id  BIGINT UNSIGNED NOT NULL,
    source_id    BIGINT UNSIGNED NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'pending',
    indexed_at   DATETIME(3) DEFAULT NULL,
    error        TEXT,
    metadata     JSON,
    created_at   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at   DATETIME(3) DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX idx_chunk_id (chunk_id),
    INDEX idx_index_name (index_name),
    INDEX idx_document_id (document_id),
    INDEX idx_source_id (source_id),
    INDEX idx_status (status),
    INDEX idx_deleted_at (deleted_at),
    INDEX idx_index_status_deleted_at (index_name, status, deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rag_retrieval_trace (
    id             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    query          TEXT NOT NULL,
    route          VARCHAR(50) NOT NULL,
    vector_count   INT NOT NULL DEFAULT 0,
    keyword_count  INT NOT NULL DEFAULT 0,
    hybrid_count   INT NOT NULL DEFAULT 0,
    latency_ms     BIGINT NOT NULL DEFAULT 0,
    metadata       JSON,
    created_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at     DATETIME(3) DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX idx_route (route),
    INDEX idx_deleted_at (deleted_at),
    INDEX idx_route_created_at (route, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rag_evidence (
    id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    evidence_key    VARCHAR(120) NOT NULL,
    query           TEXT NOT NULL,
    chunk_id        BIGINT UNSIGNED NOT NULL,
    document_id     BIGINT UNSIGNED NOT NULL,
    source_id       BIGINT UNSIGNED NOT NULL,
    channel         VARCHAR(50) NOT NULL,
    title           VARCHAR(500) NOT NULL DEFAULT '',
    content         LONGTEXT,
    location        VARCHAR(500) NOT NULL DEFAULT '',
    score           DOUBLE NOT NULL DEFAULT 0,
    rerank_score    DOUBLE NOT NULL DEFAULT 0,
    token_estimate  INT NOT NULL DEFAULT 0,
    citation_uri    VARCHAR(1000) NOT NULL DEFAULT '',
    metadata        JSON,
    created_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at      DATETIME(3) DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX idx_evidence_key (evidence_key),
    INDEX idx_chunk_id (chunk_id),
    INDEX idx_document_id (document_id),
    INDEX idx_source_id (source_id),
    INDEX idx_channel (channel),
    INDEX idx_score (score),
    INDEX idx_rerank_score (rerank_score),
    INDEX idx_deleted_at (deleted_at),
    INDEX idx_channel_score_deleted_at (channel, score, deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rag_rerank_result (
    id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    query         TEXT NOT NULL,
    model         VARCHAR(120) NOT NULL DEFAULT '',
    input_count   INT NOT NULL DEFAULT 0,
    output_count  INT NOT NULL DEFAULT 0,
    items         JSON,
    metadata      JSON,
    created_at    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at    DATETIME(3) DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX idx_model (model),
    INDEX idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rag_evidence_gate_result (
    id                 BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    query              TEXT NOT NULL,
    passed             TINYINT(1) NOT NULL DEFAULT 0,
    score              DOUBLE NOT NULL DEFAULT 0,
    reason             TEXT,
    missing_aspects    JSON,
    weak_evidence_ids  JSON,
    contradictions     JSON,
    suggestions        JSON,
    status             VARCHAR(20) NOT NULL DEFAULT 'review',
    metadata           JSON,
    created_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at         DATETIME(3) DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX idx_passed (passed),
    INDEX idx_score (score),
    INDEX idx_status (status),
    INDEX idx_deleted_at (deleted_at),
    INDEX idx_status_score_deleted_at (status, score, deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
