CREATE TABLE IF NOT EXISTS runs (
    id VARCHAR(64) NOT NULL,
    agent_id VARCHAR(64) NOT NULL DEFAULT '',
    session_id VARCHAR(64) NOT NULL DEFAULT '',
    workflow_id VARCHAR(64) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL,
    input LONGTEXT,
    output LONGTEXT,
    error LONGTEXT,
    started_at DATETIME(3),
    completed_at DATETIME(3),
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_runs_agent (agent_id),
    KEY idx_runs_session (session_id),
    KEY idx_runs_workflow (workflow_id),
    KEY idx_runs_status (status),
    KEY idx_runs_started_at (started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tool_invocations (
    id VARCHAR(64) NOT NULL,
    run_id VARCHAR(64) NOT NULL DEFAULT '',
    node_id VARCHAR(120) NOT NULL DEFAULT '',
    tool_name VARCHAR(120) NOT NULL,
    input_json LONGTEXT,
    output_json LONGTEXT,
    is_error TINYINT NOT NULL DEFAULT 0,
    latency_ms BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    full_result_ref VARCHAR(500) NOT NULL DEFAULT '',
    started_at DATETIME(3),
    completed_at DATETIME(3),
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_tool_invocations_run (run_id),
    KEY idx_tool_invocations_node (node_id),
    KEY idx_tool_invocations_tool (tool_name),
    KEY idx_tool_invocations_error (is_error),
    KEY idx_tool_invocations_status (status),
    KEY idx_tool_invocations_started_at (started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    run_id VARCHAR(64) NOT NULL DEFAULT '',
    trace_id VARCHAR(80) NOT NULL DEFAULT '',
    event_type VARCHAR(80) NOT NULL,
    tool_name VARCHAR(120) NOT NULL DEFAULT '',
    resource_type VARCHAR(80) NOT NULL DEFAULT '',
    resource_id VARCHAR(120) NOT NULL DEFAULT '',
    message VARCHAR(1000) NOT NULL DEFAULT '',
    payload_json LONGTEXT,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at DATETIME(3) DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_audit_logs_run (run_id),
    KEY idx_audit_logs_trace (trace_id),
    KEY idx_audit_logs_event (event_type),
    KEY idx_audit_logs_tool (tool_name),
    KEY idx_audit_logs_created_at (created_at),
    KEY idx_audit_logs_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
